= Quarkus - Prettytime

include::./includes/attributes.adoc[]

PrettyTime is an OpenSource time formatting library. It creates human readable, relative timestamps.

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.prettytime:quarkus-prettytime` extension first.
In your `pom.xml` file, add:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.prettytime</groupId>
    <artifactId>quarkus-prettytime</artifactId>
    <version>{quarkus-prettytime-version}</version>
</dependency>
----

== Features

=== Inject PrettyTime Singleton

A singleton `org.ocpsoft.prettytime.PrettyTime` can be injected anywhere. 

```java
// Inject PrettyTime using the default locale
@Inject PrettyTime prettyTime;
```

**Important**: Be aware that any changes to the injected `PrettyTime` object (as in calling `setLocale` or `setReference`) will reflect on the singleton and its usage in your entire application. In cases where you need to format to a specific locale we recommend you to create a new `PrettyTime` object instead.

The singleton may be referenced by the name `prettyTime` when used in a non-typesafe environment such as templates. For example, if used together with the https://quarkus.io/guides/qute-reference[Qute] templating engine:

```html
<table>
  {#for label in labels}
  <tr>
    <td>{label.name}</td>
    <td>Created {inject:prettyTime.format(label.created)}</td>
  </tr>
  {/for}
</table>
```

=== Native Support

This extension is fully supported in native mode.
