name: Quarkiverse Pre Release

on:
  pull_request:
    paths:
      - '.github/project.yml'

jobs:
  pre-release:
    name: Pre-Release
    uses: quarkiverse/.github/.github/workflows/pre-release.yml@main
    secrets: inherit
